name: Conservación de Islas
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/ejemplo_para_voluntarios .
    - name: Ejecuta objetivo principal del Makefile
      run: docker run --volume ${PWD}:/workdir islasgeci/ejemplo_para_voluntarios
